### ISSUE TITLE
MPE library for Processing 3.0?

### ISSUE THREAD

**Issue by RIMa-K** [shiffman/Most-Pixels-Ever-Processing#60]
Is there a version that will work with the new Processing 3.0? If not how can I download Processing 2.0?

Thanks!

**Comment by mactkg** [comment]
i don't know work with 3.x, but you can download 2.x here
![gyazo](https://gyazo.com/5da1247fcc57398dc02714c1619221a7.png)

http://processing.org/download

**Comment by shiffman** [comment]
There is now an updated release for Processing 3.  It will show up in the contributions manager soon.

https://github.com/shiffman/Most-Pixels-Ever-Processing/releases/tag/2.0.3

**Comment by RIMa-K** [comment]
That's great thanks!
